DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS book_authors CASCADE;

CREATE TABLE authors
(
    author_id bigint generated by default as identity,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (author_id)
);

CREATE TABLE books
(
    book_id bigint generated by default as identity,
        title varchar(255) not null,
        year integer not null,
        primary key (book_id)

);

CREATE TABLE book_authors
(
        author_id bigint not null,
        book_id bigint not null
);

alter table book_authors
       add constraint FKaplrj3g6pw72p4kceta338okj
       foreign key (book_id)
       references books;

alter table book_authors
       add constraint FK6b48wl2lxbg2dynww4yefcb4b
       foreign key (author_id)
       references authors;